### PR TITLE
Sort by item type in reviews (Fixes #304)

### LINKED ISSUE #304: Feature Request: Sort by item type in reviews
Just a nice to have; in lessons there's an option to sort which order you want to learn radicals/kanji/vocab.  Would be awesome to have the same ordering functionality in lessons.

### PR DESCRIPTION
**Pull request by zapan**
Sort by item type in reviews. Fix #304

### CODE REVIEW

**Comment by turtlemaster19** [comment]
@zapan I think if #304 were to be implemented, it should be like lessons where the user can choose any combination of Radical/Kanji/Vocab similar to the UI mockup in #201.

For example, I completely agree with #304 but I would want to use SRS stage order still, and pick a combination.

**Comment by zapan** [comment]
@turtlemaster19 You're right, that would be superb. I'll see what I can do 🤔

**Comment by turtlemaster19** [comment]
@zapan You might as well end up implementing #201 if you do that though.

**Comment by zapan** [comment]
Work in progress to implement @turtlemaster19 suggestions

**Pull request closed without merging**
