### PR TITLE
[Waiting for other PRs] Monster PR

### LINKED ISSUE #10: Level-up animation
Currently nothing happens when you level up.  We should have a satisfying level-up screen with pretty animations, and a summary of the items that you just unlocked at the next level.

### LINKED ISSUE #39: Lesson and Review reordering
Allow the user to reorder the Lessons and Reviews based on itemtype (Radical, Kanji, Vocabulary).

### LINKED ISSUE #86: Close but no cigar & disable partial answer match
Currently it's not possible to turn off the partial matching of answers (there is an option to disable cheating but i still want to have the ignore option).

My ideal would be behaviour like the "close but no cigar" user script, where a partial correct answer notifies you that you are close, but doesn't accept the answer yet and waits for the 100% correct match.

### LINKED ISSUE #177: Reviews not registering?
I've been though the other posts by this seems to not have been raised in the same way before, and not sure if it's tsurukame or wanikani issue...  But I've been stuck on same "this level" data ("time remaining", and number of known/locked radicals, Kanji, vocab) for nearly four days (level 5) - even though I'm doing reviews at  least 4-5 times a day of the same characters/words, and usually getting 100%). It's like it's stuck in a loop, with nothing getting updated?

Have tried logging in/out, and even complete delete and fresh install, and pull-down force refresh, but nothing works.

### LINKED ISSUE #201: Random Lesson Order
It would be nice to be able to sort Lessons by random instead of some combination of Radical/Kanji/Vocab.  This is implemented on the web with the option "Lesson Ordering: Shuffled".

### LINKED ISSUE #277: Reviews are not working
Hello! First of all I want to thank you fot this amazing app...It's really useful and user-friendly and it really helped me to get my lessons and reviews in order...but a month ago it stopped working for me. And it's a shame because I think it's the best app in the App Store for wanikani :(

It seems that the app cannot submit my lessons and reviews...If I do some reviews and go to the PC I see the reviews from my app weren't submitted so I have to do them again. Also, if I go to Show remaining section all the cards are blank...so it clearly can connect to wanikani.

My device is an iPhone 7. I tried to uninstall and install again but it didn't solve anything.

Some help please, I'm stuck a level 19 forever because I hardly can go to a pc to do my reviews and other apps are terrible :(

### LINKED ISSUE #304: Feature Request: Sort by item type in reviews
Just a nice to have; in lessons there's an option to sort which order you want to learn radicals/kanji/vocab.  Would be awesome to have the same ordering functionality in lessons.

### LINKED ISSUE #340: Feature Request: Add review order (from settings) to reviews screen
The review order setting is great, but I find myself frequently switching from the reviews screen to the settings screen and back to the reviews screen. 

It would be much more convenient if the review order could be set from the reviews screen itself.

For example, let's say I want to do all of the current level (most important) reviews first, then I want to do the oldest (easiest) reviews first, then I want to finish what's left in SRS order.

Or, let's say I'm doing my reviews, and I get to one I can't quite remember... I want to randomize the order to get around it, and pick it up at the end of my session. 

Or any other crazy idea which requires tweaking the reviews order while I'm in the middle of my reviews...

### LINKED ISSUE #355: Feature Request: "Longest Relative Wait" Order
Your lowest-level items are the ones that need to be reviewed most frequently in order to remember them, so weighing all items’ time in the review queue equally will make it more likely to answer wrong on low-level items compared to high-level ones.

Instead, for example, say you order by ratio, and you have an Apprentice 4 item (2 day wait to review it) that’s been sitting in your queue for a week. That item’s ratio is 3.5 (7/2), as that’s how many times longer you’ve waited to review it than recommended.

Then, say you also have a Guru 1 item (1 week wait) that’s been in queue for a month, so it has a ratio of 4 (28/7). That item then, since it has a higher ratio, has spent a longer relative time in the queue than the Apprentice item, and thus would be reviewed first under ratio sorting rules.

### LINKED ISSUE #365: SRS category deprecation
Replace the current Apprentice...Burned and fixed SRS stage checks with Started, Passed, Burned to accommodate new SRS systems.

I intend on fixing this in the combined PR, which hopefully will be stable and ready for review in a few days.

### PR DESCRIPTION
**Pull request by UInt2048**
# Dependencies and Swift conversion - thousands of lines!
## Dependency conversion
Most of this is just moving CocoaPods, which take space in the repository, to Swift Package Manager, integrated in Xcode, and updating Protobuf. This is also to aid the conversion of the project to Swift! You can safely ignore the `Pods` directory, since I didn't directly change it.

Dependency table:

| Prev. Dependency | Version & Date | New Dependency | Version & Date |
| :---: | :---: | :---: | :---: |
| [Charts](https://github.com/danielgindi/Charts) | 3.3.0 (Apr. 2019) | _same_ | 3.5.0 (Apr. 2020) |
| [FMDB](https://github.com/ccgus/fmdb) | 2.7.5 (Sep. 2018) | _same_ | 2.7.7 (May 2020) |
| [Haneke](https://github.com/Haneke/Haneke) | 1.0.2 (Jan. 2016) | [HanekeSwift](https://github.com/Haneke/HanekeSwift) | c23bb97 (Jan. 2020) |
| [Light-Untar-for-iOS](https://github.com/mhausherr/Light-Untar-for-iOS) | 0.3.0 (Mar. 2015) | [Light-Swift-Untar](https://github.com/Light-Untar/Light-Swift-Untar) | 1.0.1 (Jun. 2020) |
| [MMDrawerController](https://github.com/mutualmobile/MMDrawerController) | 0.6.0 (Apr. 2015) | _same_ | 3a2e739 (Jun. 2020) |
| [Protobuf](https://github.com/protocolbuffers/protobuf)* | 3.10.0 (Oct. 2019) | _same_ | 3.12.0 (May 2020)
| [Reachability](https://github.com/tonymillion/Reachability) | 3.2.0 (Nov. 2014) | [Reachability.swift](https://github.com/ashleymills/Reachability.swift) | 5.0.0 (Oct. 2019) |
| [Rexy](https://github.com/vadymmarkov/Rexy) | 1.0.1 (Jan. 2020) | _same_ | _same_ |

*Not yet with Swift Package Manager - https://github.com/apple/swift-protobuf/ would be the replacement, but that would require a lot more work since there's no Objective-C compatibility!

**NOTE:** Clang-Format and Swift Format are only used at build-time, and not included in the app, so they aren't in the table. However, the build phase has been updated to remove the extraneous additional shell file, `clang-format-all.sh`, by putting the commands directly there.

## Swift conversion
Swift is now the majority language of the repository - major progress on #57. However, this doesn't convert Go code. Here's the new language composition on this PR as of June 19, 2020 compared to master on the same date in classic before/after style:
Language Composition MasterLanguage Composition

For more information, see Monster Foundation #370.

# Issues fixed
This pull request should:
* Fix #10 by adding a minor level-up animation and summary
* Fix #86 by adding an exact match setting
* Fix #201 by adding lesson item order shuffle section
* Fix #277 (and closes #177 - its dupe) by implementing the final point - retrying once without the created field
* Fix #304 (and closes #39 - its dupe) by doing the same thing for review item order that has been done here for lesson item order
* Fix #340 by adding the review order and item order to the drawer controller
* Fix #355 by adding the longest & shortest relative wait order
* Fix #365 by adding support for multiple SRS systems

This PR also changes the user-displayed name of "Allow Cheating" to "Ignore Typos & Add Synonyms" since skipping reviews  clearly is "cheating" but isn't part of this setting.

### CODE REVIEW

**Comment by turtlemaster19** [comment]
@davidsansome This PR will not have any more major changes if I receive a response that the review process will begin. I am hesitant to attempt to do anything else because it has become unwieldy and there's no indication that what I have already done will be merged. In short, **I am requesting a review.**

**Comment by davidsansome** [comment]
Thanks for making all these changes - I really appreciate the amount of work that's gone into it!

But there's no way I can review such a huge single squashed commit that's got formatting changes, dependency changes, and new features all mixed together. Can you split this into separate pull requests - separate ones for each feature or bugfix and the Swift conversions?

On the CocoaPods to Swift package manager conversion: I've seen some intermittent CI failures fetching dependencies from the internet, so I'd prefer to keep all dependencies checked into this repository. That also makes builds more likely to be hermetic and reproducible. Were there any other reasons you wanted to switch to Swift package manager?

**Comment by turtlemaster19** [comment]
@davidsansome Thanks for the comment! I can definitely start to separate this until this becomes managable! I will start the PR-splitting with the Swift conversions without any of the new features.

As for Swift Package Manager, we have been using it in Tsurukame for Rexy since #259 was merged five months ago without any problems! It also makes PRs less unwieldy when updating dependencies, since it will only change the very few checksum lines that need to be updated.

If it makes you feel more comfortable, a quick Internet search didn't show any major errors with SwiftPM, and I did find this: https://developer.apple.com/documentation/swift_packages/building_apps_that_use_swift_packages_in_continuous_integration_workflows

Below are the lines in the commit on _this_ PR as it stands right now dealing with the checksums:

https://github.com/davidsansome/tsurukame/blob/aaa23ae0c6a9f809097b18726edc73c9fae775d4/ios/Tsurukame.xcodeproj/project.pbxproj#L2006-L2106

**Comment by turtlemaster19** [comment]
@davidsansome By the way, can you update the CocoaPods to the most recent available version so I don't have to make an extra PR? I have to edit the Protobuf file but I am going to need Protobuf 3.12 for it to work...

**Comment by turtlemaster19** [comment]
Until the Monster Foundation pull requests are all merged, there will be some more pushing to rebase it with the changing master.

**Comment by UInt2048** [comment]
I am going to mark ready for review again because I don't want to give the impression that I'm going to be adding more major features again... at least not until some stuff starts getting merged.

**Pull request closed without merging**
