### PR TITLE
Allow Japanese in search 

### LINKED ISSUE #272: Kanji Search No longer working
I used to be able to search for words using English, romanji, hiragana, or Kanji characters but recently the last two suddenly stopped working. It was very convenient so I hope it was just a bug and that feature is not being removed.

### PR DESCRIPTION
**Pull request by turtlemaster19**
Fix #272 by removing lowercase string check.

### CODE REVIEW

**Comment by turtlemaster19** [comment]
I'm not sure whether this actually fixes this, but it's the only thing that has been changed recently enough relating to the search items, that I know of.

**Comment by davidsansome** [comment]
Close!  But it looks like the bug was actually because I used == to compare strings (which actually compares their pointers) rather than using isEqual.

**Comment by dmikhalsky** [comment]
still doesn't work

**Comment by turtlemaster19** [comment]
@dmikhalsky 1.18 hasn't been uploaded to the App Store yet! 😉

**Comment by dmikhalsky** [comment]
> @dmikhalsky 1.18 hasn't been uploaded to the App Store yet!

OK :-) If I Have TestFlight installed, can I become a beta tester?

**Comment by davidsansome** [comment]
@dmikhalsky yes!  You can join the beta here: https://testflight.apple.com/join/Fijye2AA

**Pull request closed without merging**
