### PR TITLE
Custom review batch size

### PR DESCRIPTION
**Pull request by turtlemaster19**
Adds custom review batch size enabling the user between a queue of 3 to 10.

### CODE REVIEW

**Comment by turtlemaster19** [comment]
`didTapReviewBatchSize:` currently doesn't do anything, unlike its lesson counterpart.

**Comment by turtlemaster19** [comment]
Note that this PR affects `project.pbxproj`, but so does the Apple Watch complication.
If you have to choose which one to merge first, go ahead and merge the Watch complication. I can resolve the conflicts afterwards.

**Comment by turtlemaster19** [comment]
@davidsansome Thanks! For some reason, I missed the notification that you merged the Apple Watch Complication.

**Comment by zapan** [comment]
@turtlemaster19 didTapReviewBatchSize method does not exist

**Comment by turtlemaster19** [comment]
@zapan Build warnings are the worst... especially when they are false. ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʕ•̫͡•ʔ•̫͡•ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ

**Comment by turtlemaster19** [comment]
@zapan Thanks. David Sansome just fixed this. I didn't realize that I had actually somehow forgotten that...

**Pull request merged**
