### PR TITLE
Use SwiftPM instead of third_party for Rexy

### PR DESCRIPTION
**Pull request by turtlemaster19**
The `third_party` directory can be removed now, since Rexy is able to be installed via Swift Package Manager in Xcode. This commit does that, removing the need to keep a local copy of Rexy, since it will automatically be installed at build time.

### CODE REVIEW

**Comment by davidsansome** [comment]
I made a bunch of local UTF-8 fixes to Rexy that I didn't upstream yet (since the project looked kinda dead).  They'd need to be upstreamed before we can move this out of third_party.

**Comment by turtlemaster19** [comment]
@davidsansome, were they all in `Regex.swift`?

**Comment by davidsansome** [comment]
Yep I think so!  You should be able to diff it against the upstream one to see.

**Comment by turtlemaster19** [comment]
If that's the case, I already took care of them when https://github.com/vadymmarkov/Rexy/pull/14 was merged.

**Comment by davidsansome** [comment]
Ouch, I guess he didn't review that very well then - there were some breaking API changes in there too...

**Comment by turtlemaster19** [comment]
Oops, I figured they were needed to keep it working, since you made some fixes there that were required. Should I try to revert them, or should we leave it?

P.S. I'm not sure why CircleCI is failing, since it worked perfectly fine building locally.

**Comment by davidsansome** [comment]
You don’t have permission to save the file “repositories” in the folder “SourcePackages”." UserInfo={NSFilePath=/Users/SourcePackages/repositories

I think it's a problem with the CircleCI config - it looks like I didn't set a path that it needs somewhere.  I'll try to fix it tomorrow!

With Rexy, the biggest change was changing the return type of all the methods from String to Substring (so the caller can see the position that was matched).  It would break anybody using the package that expected them to be Strings.

**Comment by turtlemaster19** [comment]
I'm not sure on whose side it is. It looks like https://github.com/fastlane/fastlane/issues/15454

**Comment by turtlemaster19** [comment]
@davidsansome It seems they were aware, since they numbered the version 1.0 to signal the breaking changes. I resubmitted the commit to incorporate the latest changes in master. (Still failing. 😢)

**Comment by turtlemaster19** [comment]
@davidsansome Error seems to be cause by Fastlane running a command with `-derivedDataPath '/Users'`

**Comment by turtlemaster19** [comment]
@davidsansome Error seems to be cause by Fastlane running a command with `-derivedDataPath '/Users'`

**Comment by turtlemaster19** [comment]
@davidsansome Fastlane seems to be convinced that Xcode should use `/Users` as the `DerivedData` folder. Any luck with this?

**Comment by davidsansome** [comment]
Sorry I didn't get time to look at it yet!

**Comment by turtlemaster19** [comment]
@davidsansome I see you with the TestFlight stuff. 👀 It's definitely better 1-2 days.

**Comment by turtlemaster19** [comment]
Problem seems to be fastlane/fastlane#15910

**Comment by turtlemaster19** [comment]
Why do I keep accidentally closing?

**Comment by turtlemaster19** [comment]
@davidsansome It seems to still be trying to find the old Rexy. Do you know why?

**Comment by turtlemaster19** [comment]
@davidsansome, ready for review.

**Comment by turtlemaster19** [comment]
You may need to rollback to 09848b6 if you're ready before I can fix this.

**Comment by turtlemaster19** [comment]
Going to merge the changes just committed to master. Give me a few moments.

**Comment by turtlemaster19** [comment]
@davidsansome Ready for review. Tests are failing for the same reason master is - which is beyond the scope of this PR

**Comment by davidsansome** [comment]
Thanks!  Sorry again for taking my time with this one.
I'm looking at why the master tests are failing now...

**Pull request merged**
