### PR TITLE
Fix Reading Prompt Color on master

### PR DESCRIPTION
**Pull request by mzsanford**
The addition of Dark Mode support broke "light mode" by putting black text in a dark gradient:

_Before_
IMG_7CBC8B0989A7-1

So I fixed that:

_After (light mode)_
Simulator Screen Shot - iPhone 11 Pro - 2019-12-03 at 11 15 44

_After (dark mode)_
Simulator Screen Shot - iPhone 11 Pro - 2019-12-03 at 11 15 57

### CODE REVIEW

**Comment by turtlemaster19** [comment]
@indirect, does this conflict with #216?

**Comment by mzsanford** [comment]
I think this checks off "text in Review mode description, above the answer text field" which is already showing checked but appear to be broken in master. The PR for that issue (https://github.com/davidsansome/tsurukame/pull/211) introduced this because of the custom gradient background which is always dark, so the system label color does not contrast. Another possible fix is to change the background gradient in dark mode to be light, but that felt too jarring.

**Comment by turtlemaster19** [comment]
That means @indirect already fixed it in his local copy. If you're reading this, can you submit that stuff?

**Comment by davidsansome** [comment]
Thanks!

**Pull request merged**
