### PR TITLE
Version updates

### PR DESCRIPTION
**Pull request by UInt2048**
This PR updates versions, and only versions, of dependencies.

Here's what changed:
* Circle CI config (via editing)
    * Google Cloud CLI 1.8.3 → 1.8.4
    * Go 1.12 → 1.14
    * Xcode 11.3.0 → 11.6.0
* Gems (via bundle update)
    * Fastlane 2.150.0.rc3 → 2.154.0
* CocoaPods (via pod update)
    * Charts 3.3.0 → 3.5.0
    * SwiftFormat 0.44.0 → 0.45.2

### CODE REVIEW

**Comment by UInt2048** [comment]
Ready for review. No further changes will be made to this PR if it takes a reasonable time. This is as small as possible for a dependency update! 😉

**Comment by davidsansome** [comment]
> The CI error is just from lingering old data - not much I can do about that!

This one?

```
❌  /Users/distiller/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/Protobuf/Protobuf.framework/Headers/GPBAny.pbobjc.h:48:11: duplicate interface definition for class 'GPBAnyRoot'

GPB_FINAL @interface GPBAnyRoot : GPBRootObject
```

I get the same error when I checkout this PR and build it locally - so I think it's a real error. Can you see if you can fix it?

**Comment by UInt2048** [comment]
@davidsansome Oops, you're right. I needed to re-compile (but not make changes to) the Protobuf source files.

**Comment by davidsansome** [comment]
> @davidsansome Oops, you're right. I needed to re-compile (but not make changes to) the Protobuf source files.

Looks like it's still failing on circleci: https://app.circleci.com/pipelines/github/davidsansome/tsurukame/285/workflows/f644306c-679f-424f-b920-7f1f2bd62fc7/jobs/819/parallel-runs/0/steps/0-105 - what was the actual problem?

**Comment by UInt2048** [comment]
The actual issue is https://github.com/protocolbuffers/protobuf/issues/7772.

I believe I can resolve this dilemma by presenting the updates without Protobuf now, and then a separate request including a Swift conversion on our side along with the Protobuf update. Would this be acceptable?

**Pull request merged**
