### PR TITLE
Allow skipping (Fixes #42)

### LINKED ISSUE #42: allow skipping
slightly different than #18 
allow skipping a card BEFORE entering a bad answer (and let that card pop up again later on)
that way we can breeze through everything we're sure of quickly, and take some time later for the tougher ones...

### PR DESCRIPTION
**Pull request by zapan**
Fix davidsansome/tsurukame#42, allow skipping a card BEFORE entering a bad answer

### CODE REVIEW

**Comment by zapan** [comment]
Ok, I promise there will be no more commits from my side 😅

**Comment by zapan** [comment]
Do you want a switch in 'Reviews Settings' to enable or disable this functionality?

**Comment by zapan** [comment]
Ready for review @davidsansome. If you prefer another icon for the **Skip Review** button, don't hesitate to tell me. I've exported the current icon from the [**SF Symbols**](https://developer.apple.com/design/resources/#sf-symbols) library.

**Comment by turtlemaster19** [comment]
@davidsansome Can you please consider this?

**Comment by davidsansome** [comment]
Thanks for this!  There were a few things that weren't quite right, but I've fixed them in eeaecc97f484d74c2f314809b875c66bb25e6cb6!

**Comment by zapan** [comment]
Cool, thanks! 😀

**Pull request merged**
